name: The Pulse
favicon: null
layout_spectrum: 0
typography_spectrum: 0.56232
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f2f2f2'
    - '#939393'
    - '#383838'
    - '#76602d'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
